import { useEffect, useRef } from "react";
import type { PlaybackItem } from "./playback-sequence";
import { usePlayback } from "./usePlayback";

export function PlaybackPlayer({ items, onExit, reducedMotion = false }: { items: PlaybackItem[]; onExit: () => void; reducedMotion?: boolean }) {
  const controller = usePlayback(items, { photoDurationMs: 5000, onExit });
  const videoRef = useRef<HTMLVideoElement>(null);
  useEffect(() => { if (controller.isPlaying && controller.currentItem?.mediaType === "video") void videoRef.current?.play().catch(() => undefined); else videoRef.current?.pause(); }, [controller.currentItem, controller.isPlaying]);
  if (!items.length) return <section className="playback-empty"><p>There is nothing to play yet.</p><button type="button" onClick={onExit}>Exit</button></section>;
  const item = controller.currentItem!;
  const stickerAssets = new Map((item.stickerAssets ?? []).map((asset) => [asset.id, asset]));
  return <section className={`playback-player ${reducedMotion ? "reduced-motion" : ""}`} aria-label="Scrapbook playback"><header className="playback-header"><div><p className="eyebrow">Now turning</p><h2>{item.albumName}</h2></div><button type="button" className="playback-exit" onClick={onExit} aria-label="Exit playback">Exit</button></header><div className="playback-page"><div className="playback-media">{item.mediaType === "video" ? <video ref={videoRef} src={item.fileUrl} aria-label={item.originalName} onEnded={controller.next} playsInline /> : <img src={item.fileUrl} alt={item.originalName} />}{item.stickerPlacements.map((placement) => { const asset = stickerAssets.get(placement.stickerAssetId); return asset ? <img key={placement.id} className="playback-sticker" src={asset.fileUrl} alt={asset.originalName} style={{ left: `${placement.x}%`, top: `${placement.y}%`, zIndex: placement.layer, transform: `translate(-50%, -50%) scale(${placement.scale}) rotate(${placement.rotation}deg)` }} /> : null; })}</div><div className="playback-caption">{item.caption && <p>“{item.caption}”</p>}{item.location && <small>{item.location}</small>}<small>{item.originalName}</small></div></div><div className="playback-controls"><button type="button" onClick={controller.previous} aria-label="Previous item">←</button>{controller.isComplete ? <button type="button" className="button-primary" onClick={controller.replay}>Replay</button> : controller.isPlaying ? <button type="button" className="button-primary" onClick={controller.pause} aria-label="Pause playback">Pause</button> : <button type="button" className="button-primary" onClick={controller.play} aria-label="Play playback">Play</button>}<button type="button" onClick={controller.next} aria-label="Next item">→</button><span className="playback-progress">{controller.currentIndex + 1} / {items.length}</span></div></section>;
}
