import { randomUUID } from "node:crypto";
import { createReadStream } from "node:fs";
import fs from "node:fs/promises";
import formidable, { type FormidableFields, type FormidableFile, type FormidableFiles } from "formidable";
import { Router, type Request } from "express";
import { requireSession } from "../auth/middleware.js";
import type { TransactionalDatabase } from "../auth/sessions.js";
import { AppError } from "../errors.js";
import { requireScrapbookRole } from "../scrapbooks/permissions.js";
import type { MediaStorage } from "../storage/storage.js";
import { DEFAULT_MAX_STICKER_BYTES, validateUploadedFile, type UploadedFile } from "../media/validation.js";
import { createStickerAsset, createStickerPlacement, deleteStickerAsset, deleteStickerPlacement, findStickerAsset, listStickerAssets, listStickerPlacements, normalizePlacement, reorderStickerPlacements, updateStickerPlacement } from "./repository.js";

function param(request: Request, name: string): string { const value = request.params[name]; if (typeof value !== "string" || !value) throw new AppError(400, `${name} is required`, "INVALID_INPUT"); return value; }
function bodyRecord(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new AppError(400, "Request body must be an object", "INVALID_INPUT"); return value as Record<string, unknown>; }
function oneField(fields: FormidableFields, name: string): string | undefined { const value = fields[name]; if (value === undefined) return undefined; if (value.length !== 1) throw new AppError(400, `${name} must be provided once`, "INVALID_INPUT"); return value[0]; }
function oneFile(files: FormidableFiles): FormidableFile { const value = files.file; const file = Array.isArray(value) ? value[0] : value; if (!file) throw new AppError(400, "A sticker file is required", "FILE_REQUIRED"); return file; }
async function cleanup(files: FormidableFiles | undefined) { if (!files) return; const paths = Object.values(files).flatMap((value) => (Array.isArray(value) ? value : value ? [value] : []).map((file) => file.filepath)); await Promise.all([...new Set(paths)].map((path) => fs.rm(path, { force: true }).catch(() => undefined))); }
function parseUpload(request: Request, maxFileSize: number): Promise<{ fields: FormidableFields; files: FormidableFiles }> { return new Promise((resolve, reject) => { formidable({ allowEmptyFiles: false, keepExtensions: true, maxFileSize, maxFiles: 1, multiples: false }).parse(request, (error, fields, files) => { if (error) { void cleanup(files).finally(() => reject(error.code === 1016 || error.code === 1009 ? new AppError(413, `The uploaded sticker exceeds the ${maxFileSize}-byte limit`, "UPLOAD_TOO_LARGE") : new AppError(400, "The multipart upload is invalid", "INVALID_UPLOAD"))); return; } resolve({ fields, files }); }); }); }
function toUploadedFile(file: FormidableFile): UploadedFile { return { filepath: file.filepath, originalFilename: file.originalFilename, mimetype: file.mimetype, size: file.size }; }
function storageKey(originalName: string): string { const extension = originalName.match(/\.[a-z0-9]{1,8}$/i)?.[0].toLowerCase() ?? ".bin"; return `sticker-${randomUUID()}${extension}`; }
function publicAsset(asset: Awaited<ReturnType<typeof listStickerAssets>>[number]) { const { storageKey: _storageKey, createdBy: _createdBy, scrapbookId: _scrapbookId, ...rest } = asset; return { ...rest, fileUrl: `/api/files/by-sticker/${encodeURIComponent(asset.id)}`, createdAt: asset.createdAt.toISOString() }; }
function publicPlacement(placement: Awaited<ReturnType<typeof listStickerPlacements>>[number]) { const { scrapbookId: _scrapbookId, ...rest } = placement; return rest; }
function numberValue(value: unknown, field: string, fallback = 0): number { if (value === undefined) return fallback; if (typeof value !== "number" || !Number.isFinite(value)) throw new AppError(400, `${field} must be a number`, "INVALID_PLACEMENT"); return value; }

export function createStickerRouter({ db, storage, config = {} }: { db: TransactionalDatabase; storage: MediaStorage; config?: { maxStickerBytes?: number } }): Router {
  const router = Router(); router.use(requireSession(db));
  router.get("/:scrapbookId", requireScrapbookRole(db, ["owner", "editor"]), async (request, response, next) => { try { response.json({ assets: (await listStickerAssets(db, param(request, "scrapbookId"))).map(publicAsset) }); } catch (error) { next(error); } });
  router.post("/:scrapbookId", requireScrapbookRole(db, ["owner", "editor"]), async (request, response, next) => { let files: FormidableFiles | undefined; try { const scrapbookId = param(request, "scrapbookId"); const parsed = await parseUpload(request, config.maxStickerBytes ?? DEFAULT_MAX_STICKER_BYTES); files = parsed.files; const upload = await validateUploadedFile(toUploadedFile(oneFile(files)), "sticker", { maxBytes: config.maxStickerBytes ?? DEFAULT_MAX_STICKER_BYTES }); const key = storageKey(upload.originalName); const stored = await storage.put({ key, source: createReadStream(upload.filepath), byteSize: upload.byteSize }); try { const created = await createStickerAsset(db, { scrapbookId, storageKey: stored.key, originalName: upload.originalName, mimeType: upload.mimeType, byteSize: stored.byteSize, createdBy: request.auth!.userId }); response.status(201).json({ asset: publicAsset(created) }); } catch (error) { await storage.delete(stored.key).catch(() => undefined); throw error; } } catch (error) { next(error); } finally { await cleanup(files); } });
  router.delete("/:scrapbookId/:assetId", requireScrapbookRole(db, ["owner", "editor"]), async (request, response, next) => { try { const scrapbookId = param(request, "scrapbookId"); const assetId = param(request, "assetId"); const existing = await findStickerAsset(db, scrapbookId, assetId); if (!existing) { next(new AppError(404, "Sticker asset was not found", "NOT_FOUND")); return; } await storage.delete(existing.storageKey).catch(() => { throw new AppError(503, "Sticker file could not be removed; retry the operation", "STORAGE_CLEANUP_FAILED"); }); const deleted = await deleteStickerAsset(db, scrapbookId, assetId); if (!deleted) { next(new AppError(404, "Sticker asset was not found", "NOT_FOUND")); return; } response.status(204).send(); } catch (error) { next(error); } });
  router.get("/:scrapbookId/placements/:albumId", requireScrapbookRole(db, ["owner", "editor"]), async (request, response, next) => { try { response.json({ placements: (await listStickerPlacements(db, param(request, "scrapbookId"), param(request, "albumId"))).map(publicPlacement) }); } catch (error) { next(error); } });
  router.post("/:scrapbookId/placements/:albumId", requireScrapbookRole(db, ["owner", "editor"]), async (request, response, next) => { try { const input = bodyRecord(request.body); const values = normalizePlacement({ x: numberValue(input.x, "x"), y: numberValue(input.y, "y"), scale: numberValue(input.scale, "scale", 1), rotation: numberValue(input.rotation, "rotation"), layer: numberValue(input.layer, "layer") }); const created = await createStickerPlacement(db, { scrapbookId: param(request, "scrapbookId"), albumId: param(request, "albumId"), stickerAssetId: typeof input.stickerAssetId === "string" ? input.stickerAssetId : "", ...values }); response.status(201).json({ placement: publicPlacement(created) }); } catch (error) { next(error); } });
  router.patch("/:scrapbookId/placements/:albumId/:placementId", requireScrapbookRole(db, ["owner", "editor"]), async (request, response, next) => { try { const input = bodyRecord(request.body); const updates = { x: numberValue(input.x, "x", NaN), y: numberValue(input.y, "y", NaN), scale: numberValue(input.scale, "scale", NaN), rotation: numberValue(input.rotation, "rotation", NaN), layer: numberValue(input.layer, "layer", NaN) }; const filtered = Object.fromEntries(Object.entries(updates).filter(([, value]) => Number.isFinite(value))); const updated = await updateStickerPlacement(db, param(request, "scrapbookId"), param(request, "albumId"), param(request, "placementId"), filtered); if (!updated) { next(new AppError(404, "Sticker placement was not found", "NOT_FOUND")); return; } response.json({ placement: publicPlacement(updated) }); } catch (error) { next(error); } });
  router.delete("/:scrapbookId/placements/:albumId/:placementId", requireScrapbookRole(db, ["owner", "editor"]), async (request, response, next) => { try { const removed = await deleteStickerPlacement(db, param(request, "scrapbookId"), param(request, "albumId"), param(request, "placementId")); if (!removed) { next(new AppError(404, "Sticker placement was not found", "NOT_FOUND")); return; } response.status(204).send(); } catch (error) { next(error); } });
  router.post("/:scrapbookId/placements/:albumId/reorder", requireScrapbookRole(db, ["owner", "editor"]), async (request, response, next) => { try { const input = bodyRecord(request.body); if (!Array.isArray(input.orderedIds) || input.orderedIds.some((id) => typeof id !== "string")) throw new AppError(400, "orderedIds must contain placement IDs", "INVALID_ORDER"); await reorderStickerPlacements(db, param(request, "scrapbookId"), param(request, "albumId"), input.orderedIds as string[]); response.status(204).send(); } catch (error) { next(error); } });
  return router;
}
